Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -21,7 +21,7 @@ commands:
             command: | 
               echo "Destroying eks cluster after deployment failure"
               eksctl delete cluster --region=us-east-1 --name=udacity-capstone-cluster
-              echo ""EKS cluster and nodes successfully destroyed. For error see build-stage output""
+              echo ""EKS cluster and nodes successfully destroyed"
 
 jobs:
   
@@ -248,39 +248,6 @@ jobs:
       
       - eks-cluster-destroy
 
-
-#  deploy-to-eks:
-#    docker:
-#      - image: cimg/python:3.10
-#    steps:
-#      - checkout
-#      - kubernetes/install-kubectl:
-#            kubectl-version: v1.25.2
-#      - aws-eks/update-kubeconfig-with-authenticator:
-#            cluster-name: udacity-capstone-cluster
-#      - run:
-#          name: test
-#          command: |
-#            kubectl get services
-#            ls
-#      - kubernetes/create-or-update-resource:
-#          get-rollout-status: true
-#          resource-file-path: ./.circleci/files/deployment.yml
-#          resource-name: frenkell/udacity-capstone
-#          show-kubectl-command: true
-#      - run:
-#          name: store app endpoint and old
-#          working_directory: ./.circleci/files
-#          command: |
-#            kubectl get services
-#            api=$(kubectl get services udacity-capstone:ver-${CIRCLE_WORKFLOW_ID:0:5} --output jsonpath='{.status.loadBalancer.ingress[0].hostname}')
-#            echo $api >> capstone-endpoint.txt
-#            cat app-endpoint.txt
-#      - persist_to_workspace:
-#          root: ~/
-#          paths:
-#            - .circleci/files/capstone-endpoint.txt
-
   smoke-test:
     docker:
       - image: cimg/python:3.10
@@ -311,14 +278,16 @@ jobs:
           name: Smoke test
           working_directory: ./.circleci/files
           command: |
-            export APP_IP=$(cat capstone-endpoint.txt)    
-            export APP_ENDPOINT="http://${APP_IP}:5000"
-            echo ${APP_ENDPOINT}
-            if curl --head ${APP_ENDPOINT} | grep "HTTP/1.1 200 OK"
+            export CAPSTONE_IP=$(cat capstone-endpoint.txt)    
+            export CAPSTONE_ENDPOINT="http://${APP_IP}:5000"
+            echo "Endpoint = ${CAPSTONE_ENDPOINT}"
+            if curl --head ${CAPSTONE_ENDPOINT} | grep "HTTP/1.1 200 OK"
             then
-              return 0
+              exit 0
+              echo "smoke test performed successfully"
             else
-              return 1
+              exit 1
+              echo "smoke test failed"
             fi
 
 workflows:
